In [1]:
import pandas as pd
import yfinance as yf

In [2]:
nifty_50_data = pd.read_csv("../data/input/nifty_50.csv")

In [3]:
print(f"Shape of nifty 50 data: Rows: {nifty_50_data.shape[0]}, Columns: {nifty_50_data.shape[1]}")

Shape of nifty 50 data: Rows: 4554, Columns: 12

In [4]:
nifty_50_data.describe()

,Open,High,Low,Close,Volume,Change_%,Range,Range_%,Gap,Gap_%
count,4554.000000,4554.000000,4554.000000,4554.000000,4.554000e+03,4554.000000,4554.000000,4554.000000,4554.000000,4554.000000
mean,11124.661552,11183.204467,11050.708154,11118.391542,2.144758e+05,0.045144,132.496311,1.437145,10.513362,0.095314
std,6509.787505,6529.477155,6484.132221,6507.488984,2.061453e+05,1.303409,98.616696,1.251011,75.128327,0.583347
min,2553.600098,2585.300049,2252.750000,2524.199951,0.000000e+00,-12.980500,21.850000,0.250000,-1146.050000,-9.140000
25%,5704.137695,5735.562378,5660.375000,5698.237427,0.000000e+00,-0.525675,71.300000,0.760000,-6.125000,-0.070000
50%,8794.574707,8823.099609,8733.250000,8776.575195,1.913500e+05,0.062500,104.950000,1.090000,6.850000,0.080000
75%,15916.887695,16022.149902,15829.862793,15913.837891,2.981750e+05,0.654725,164.250000,1.660000,34.150000,0.320000
max,26333.699219,26373.199219,26210.050781,26328.550781,1.811000e+06,17.744100,1898.050000,19.360000,1219.650000,6.380000

In [5]:
nifty_50_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4554 entries, 0 to 4553
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4554 non-null   str
 1   Open      4554 non-null   float64
 2   High      4554 non-null   float64
 3   Low       4554 non-null   float64
 4   Close     4554 non-null   float64
 5   Volume    4554 non-null   int64
 6   Change_%  4554 non-null   float64
 7   Trend     4554 non-null   str
 8   Range     4554 non-null   float64
 9   Range_%   4554 non-null   float64
 10  Gap       4554 non-null   float64
 11  Gap_%     4554 non-null   float64
dtypes: float64(9), int64(1), str(2)
memory usage: 507.1 KB

In [6]:
nifty_50_data.head()

,Date,Open,High,Low,Close,Volume,Change_%,Trend,Range,Range_%,Gap,Gap_%
0,2026-04-13,23589.599609,23907.400391,23555.599609,23842.650391,488800,-0.8646,Negative,351.80,1.49,-461.00,-1.92
1,2026-04-10,23880.550781,24074.050781,23856.349609,24050.599609,481300,1.1588,Positive,217.70,0.91,105.45,0.44
2,2026-04-09,23909.050781,23990.750000,23682.800781,23775.099609,466600,-0.9261,Negative,307.95,1.30,-88.30,-0.37
3,2026-04-08,23855.150391,24025.150391,23828.500000,23997.349609,639300,3.7784,Positive,196.65,0.83,731.50,3.16
4,2026-04-07,22838.699219,23153.849609,22719.300781,23123.650391,477000,0.6766,Positive,434.55,1.91,-129.55,-0.56

In [7]:
nifty_50_data.tail()

,Date,Open,High,Low,Close,Volume,Change_%,Trend,Range,Range_%,Gap,Gap_%
4549,2007-09-21,4752.950195,4855.700195,4733.700195,4837.549805,0,1.8957,Positive,122.00,2.58,5.40,0.11
4550,2007-09-20,4734.850098,4760.850098,4721.149902,4747.549805,0,0.3212,Positive,39.70,0.84,2.50,0.05
4551,2007-09-19,4550.250000,4739.000000,4550.250000,4732.350098,0,4.0946,Positive,188.75,4.15,4.05,0.09
4552,2007-09-18,4494.100098,4551.799805,4481.549805,4546.200195,0,1.1469,Positive,70.25,1.57,-0.55,-0.01
4553,2007-09-17,4518.450195,4549.049805,4482.850098,4494.649902,0,0.0000,Neutral,66.20,1.48,0.00,0.00

In [8]:
nifty_50_data.isnull().sum()

Date        0
Open        0
High        0
Low         0
Close       0
Volume      0
Change_%    0
Trend       0
Range       0
Range_%     0
Gap         0
Gap_%       0
dtype: int64

In [9]:
# Simple moving average
nifty_50_data["SMA_20"] = nifty_50_data["Close"].rolling(20).mean()

# RSI (simple)
delta = nifty_50_data["Close"].diff()
gain = delta.clip(lower=0).rolling(14).mean()
loss = (-delta.clip(upper=0)).rolling(14).mean()
rs = gain / loss
nifty_50_data["RSI"] = 100 - (100 / (1 + rs))

In [10]:
nifty_50_data

,Date,Open,High,Low,Close,Volume,Change_%,Trend,Range,Range_%,Gap,Gap_%,SMA_20,RSI
0,2026-04-13,23589.599609,23907.400391,23555.599609,23842.650391,488800,-0.8646,Negative,351.80,1.49,-461.00,-1.92,NaN,NaN
1,2026-04-10,23880.550781,24074.050781,23856.349609,24050.599609,481300,1.1588,Positive,217.70,0.91,105.45,0.44,NaN,NaN
2,2026-04-09,23909.050781,23990.750000,23682.800781,23775.099609,466600,-0.9261,Negative,307.95,1.30,-88.30,-0.37,NaN,NaN
3,2026-04-08,23855.150391,24025.150391,23828.500000,23997.349609,639300,3.7784,Positive,196.65,0.83,731.50,3.16,NaN,NaN
4,2026-04-07,22838.699219,23153.849609,22719.300781,23123.650391,477000,0.6766,Positive,434.55,1.91,-129.55,-0.56,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4549,2007-09-21,4752.950195,4855.700195,4733.700195,4837.549805,0,1.8957,Positive,122.00,2.58,5.40,0.11,5230.809985,21.472022
4550,2007-09-20,4734.850098,4760.850098,4721.149902,4747.549805,0,0.3212,Positive,39.70,0.84,2.50,0.05,5207.422485,12.219281
4551,2007-09-19,4550.250000,4739.000000,4550.250000,4732.350098,0,4.0946,Positive,188.75,4.15,4.05,0.09,5176.489990,13.086910
4552,2007-09-18,4494.100098,4551.799805,4481.549805,4546.200195,0,1.1469,Positive,70.25,1.57,-0.55,-0.01,5125.835010,12.174905
4553,2007-09-17,4518.450195,4549.049805,4482.850098,4494.649902,0,0.0000,Neutral,66.20,1.48,0.00,0.00,5067.165015,14.931373